# Generated by Django 4.2.5 on 2024-01-07 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'Товар-Заказ', 'verbose_name_plural': 'Товары-Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 11, 59, 17, 109699, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='count',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
