# Generated by Django 4.2.5 on 2024-01-08 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_productorder_options_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_transport',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата провоза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 8, 14, 3, 44, 604745, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to='products', verbose_name='Фото'),
        ),
    ]
